### ISSUE TITLE
Occasionally the "Creating repository in /tmp/packages" step will freeze when qemu-user-static is used for pkg-static

### ISSUE THREAD

**Issue by CyberBotX** [freebsd/poudriere#1009]
## Prerequisites
- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version? (running poudriere-devel-3.3.99.20220713)
- [x] Is your ports tree recent?
- [x] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
I use poudriere on an amd64 host to build aarch64 packages for my Raspberry Pi 4. I have my packages signed with a signing key. Occasionally, when poudriere is creating the temporary pkg repository, it will get stuck at 0% and never progress. When I check my running processes, I can see that it was trying to call the build jail's pkg-static, which in turn means it needs to call qemu-aarch64-static to run it. The only solution I've found thus far was to copy the amd64 host's version of /usr/local/sbin/pkg-static over to the jail on top of ${PKG_BIN}, that allowed that step to complete successfully.

## How to reproduce
Inconsistently:
1) Build aarch64 packages on an amd64 host.
2) Wait for the packages to be built.
3) poudriere will get stuck when pkg-static repo is called to create the repository.

## Expected behavior
I believe that poudriere should never use the jail's pkg-static for creating the repo, but instead should always use the host's pkg-static instead.

## Environment
 - Host OS [e.g. 12.2 amd64]: 13.0 amd64
 - Jail OS [e.g. 12.0 powerpc]: 13.0 aarch64
 - Poudriere Version [e.g. 3.3.1 or git hash or port version]: devel-3.3.99.20220713
 - Ports branch and revision [e.g. 2020Q3 r550754]: main efaee70d4ec6

**Comment by larsve** [comment]
I've just had the same issue when cross-building ARM packages, my issue were because I had an older PKG version inside the jail. When I updated the ports-tree used for building packages to have the same version as my host, it worked for me.

As far as I can see, poudriere check that it's the same PKG version in the jail, as on the host, before replacing the jail (ARM) pkg-static, with the (AMD64) pkg-static from the host.

If anyone else stumbles on this issue, check that the PKG version built in the jail, is the same version as on the host.

**Comment by and3r00** [comment]
How do I check the pkg version in jail? This is stopping me from being able to do anything.

**Comment by chrullrich** [comment]
It seems to me that this version check fails whenever `ports-mgmt/pkg` has a PORTREVISION:

    injail_ver=$(realpath "${MASTERMNT}/packages/Latest/pkg.${PKG_EXT}")
    injail_ver=${injail_ver##*/}
    injail_ver=${injail_ver##*-}
    injail_ver=${injail_ver%.*}

Right now, `pkg` is 1.20.9_1 in main, and there is no provision for getting rid of the "_1".

**Comment by nreilly** [comment]
I'm getting this with poudriere-git-3.4.99.20240105
Enabling debug output doesn't provide anything useful.

[00:03:35] Stopping 2 builders
[00:03:36] Creating pkg repository
Creating repository in /tmp/packages:   0%

Host OS: 14.0 amd64
Jail OS: 13.2 aarch64, 14.0 aarch64

However, it works fine with 13.2 amd64

**Comment by nreilly** [comment]
I wonder if this happens when new prebuilt packages for pkg are available for amd64 before aarch64.

**Comment by madpilot78** [comment]
Hi,

I'm getting a very similar problem recently in my poudriere, also cross compiling for arm64. I reported it in the mailing lists:

https://lists.freebsd.org/archives/freebsd-arm/2024-January/003680.html

While there is not much new information there, my first hunch has been to blame qemu-user-static, but maybe that's unrelated, I really don't know.

@chrullrich I don't where that check is, but pkg-repo (arm64 binary) gets called and stalls in my case, so whatever version check it looks like it is passed.

**Comment by chrullrich** [comment]
I don't know the root cause, i.e. why the aarch64 `pkg` binary does not work, but the failing version check is definitely the reason I'm seeing this problem. I reverted `ports-mgmt/pkg` to 1.20.9 (without the PORTREVISION) and the repo signing immediately started working again.

From my logs, it had stopped working on 24 January, in the first bulk run after the commit that added the PORTREVISION. @madpilot78, you mention in https://lists.freebsd.org/archives/freebsd-arm/2024-January/003681.html that it last worked for you "around 20th December", any chance you meant January?

As far as I know, the fact that the binary that is run is an arm64 one is actually evidence that the version check does _not_ pass, because if it did, the host's amd64 binary would be copied.

The check is somewhere in `/usr/local/share/poudriere/common.sh`, IIRC.

**Comment by madpilot78** [comment]
@chrullrich 

> https://github.com/freebsd/poudriere/issues/1009#issuecomment-1914404197 that it last worked for you "around 20th December", any chance you meant January?

I am sure the last time I rebuilt my arm64 (for RPi3) image was on 20th December. I have been busy, then away for a week, then ill for another week, so I did not make any new arm64 builds up until around 23rd January. So I DID mean 20th December, but it is quite possible that it broke around 20th January, since I did not try to build arm64 packages for a while.


Anyway if the only real problem is the failing check on the pkg version that should not be too difficult to fix in poudriere. I'll investigate that.

As a sidenote, the arm64 binary should work though, so a bug in qemu-static should be investigated anyway in this case. But this is not a bug in poudriere, so unrelated here.

**Comment by madpilot78** [comment]
Created a pull request addressing the issue as described by @chrullrich 

Allows poudriere to use native pkg-static when version is the same, ignores the PORTREVISION, since `pkg-static -v` output returns no information about that.

Works quite fine here.

**Comment by artooro** [comment]
Should it work to patch an existing install? I applied the patch from https://github.com/freebsd/poudriere/commit/6a094f539541791670e8e15a555526e8d14b8afb to `/usr/local/share/poudriere/common.sh` on the system and it has not solved the problem.
Do I need to re-create the ARM jails?

**Comment by madpilot78** [comment]
@artooro

It should work with an existing build, and also, pkg has been updated and the old version check should work fine again too.

Are you sure your issue is exactly the one described here? This is a very specific edge case.

**Comment by artooro** [comment]
@madpilot78 the symptoms appear the same. The amd64 jail works fine, but both my armv6 and arm64.aarch64 builds fail with `Creating repository in /tmp/packages`
And this is a fresh freebsd 14.0 install.
Now for ports I'm using a [pfSense branch](https://github.com/pfsense/FreeBSD-ports/blob/RELENG_2_7_2/ports-mgmt/pkg/Makefile) which has pkg 1.20.8_3. Maybe I'll test with the freebsd 14 ports tree as well.

**Comment by madpilot78** [comment]
Most probably the version of pkg in your set is different from the native one on the build machine, so poudriere is trying to use the packaged one. Yes you should try using a ports tree that includes the same exact version of pkg that you have installed on the build machine.
