### ISSUE TITLE
poudriere doesn't work in a jail

### ISSUE THREAD

**Issue by bapt** [freebsd/poudriere#216]
It is not possible to start poudriere bulk within a jail:
```
# poudriere bulk -f /usr/local/etc/poudriere.d/ports-lists/Kunden-Ports -j Kunden

[00:00:00] ====>> Creating the reference jail... done
[00:01:04] ====>> Mounting system devices for Kunden-default
[00:01:04] ====>> Mounting ports/packages/distfiles
[00:01:04] ====>> Using packages from previously failed build
[00:01:04] ====>> Mounting packages from: /poudriere/data/packages/Kunden-default
[00:01:04] ====>> Mounting /var/db/ports from: /usr/local/etc/poudriere.d/Kunden-options
[00:01:04] ====>> Appending to make.conf: /usr/local/etc/poudriere.d/Kunden-make.conf
/etc/resolv.conf -> /poudriere/data/.m/Kunden-default/ref/etc/resolv.conf
[00:01:04] ====>> Starting jail Kunden-default
jail: jail_set: Operation not permitted
[00:01:04] ====>> Cleaning up
[00:01:04] ====>> Umounting file systems
```
I've followed the wiki-entry as much as possible, but i do not use ZFS. Therefore my FreeBSD 10 config for the jail looks like:
```
poudriere {
  path="/usr/local/jail/poudriere";
  host.hostname="poudriere";
  ip6.addr="2a01:4f8:150:50a5::12/64";
        persist;
        children.max=99;
        allow.mount;
        allow.mount.devfs;
        allow.mount.procfs;
        allow.mount.zfs;
        allow.mount.nullfs;
        allow.mount.tmpfs;
        allow.raw_sockets;
        allow.socket_af;
        allow.sysvipc;
        allow.chflags;
        mount.devfs;
        enforce_statfs=1; 
  interface=re0;
  exec.start = "/bin/sh /etc/rc";
  exec.stop = "/bin/sh /etc/rc.shutdown";

}
```
The error message indicates that it is not possible to create a jail within a jail. Therefore i tried it manually - i'm able to create a jail within a jail- poudriere not.

If you have IPv6 it is possible to give you access to the jail for further testing.

**Comment by yurivict** [comment]
I think this is a bug in poudriere that build of pkg succeeds in poudriere, while it fails with port make on the freshly installed system. poudriere should behave like build is done on the freshly installed system.

**Comment by gynter** [comment]
**The issue is not related to the Poudriere, but to the design of FreeBSD jails. Since this issue report is the first one which pops up in search engines I'll put the solution to here.**

#### Issue/error
```
[00:00:00] ====>> Creating the reference jail... done
[00:00:04] ====>> Mounting system devices for 10-1R_amd64-default
[00:00:04] ====>> Mounting ports/packages/distfiles
[00:00:04] ====>> Using packages from previously failed build
[00:00:04] ====>> Mounting packages from: /poudriere/data/packages/10-1R_amd64-default
[00:00:04] ====>> Appending to make.conf: /usr/local/etc/poudriere.d/10-1R_amd64-make.conf
/etc/resolv.conf -> /poudriere/data/.m/10-1R_amd64-default/ref/etc/resolv.conf
[00:00:04] ====>> Starting jail 10-1R_amd64-default
jail: jail_set: Operation not permitted
[00:00:04] ====>> Cleaning up
[00:00:04] ====>> Umounting file systems
```

#### Description

From `man jail`:

> Jailed processes are not allowed to confer greater permissions than they
> themselves are given, e.g., if a jail is created with allow.nomount, it
> is not able to create a jail with allow.mount set.  Similarly, such
> restrictions as ip4.addr and securelevel may not be bypassed in child
> jails.

Therefore one must define IP addresses `127.0.0.1` and `::1` for 
`loopback` interface `lo0` in the super jail system (Poudriere jail). Same goes with any other IP address, You can only use the IP's for hierarchical jails which are set for the super jail.

#### Test (on 10.1-STABLE)

When running, this one gets the error stated above:

```
# jail -c persist 'name=10-1R_amd64-default' \ 
'path=/poudriere/data/.m/10-1R_amd64-default/ref' \ 
'host.hostname=10-1R_amd64-default' \ 
'ip4.addr=127.0.0.1'  'ip6.addr=::1' \ 
allow.socket_af allow.raw_sockets allow.chflags allow.sysvipc
```

Runnig the code below goes without issues (You can see that 
`'ip4.addr=127.0.0.1' 'ip6.addr=::1'` params are removed):

```
# jail -c persist 'name=10-1R_amd64-default' \ 
'path=/poudriere/data/.m/10-1R_amd64-default/ref' \ 
'host.hostname=10-1R_amd64-default' \ 
allow.socket_af allow.raw_sockets allow.chflags allow.sysvipc
```

The test can be reproduced by removing `${network}` variable from line 
252 of `/usr/local/share/poudriere/common.sh`.

#### Solution (for `ezjail` only, but same method can be applied to `/etc/jail.conf`)

Append `127.0.0.1,::1` to the jail IP list in 
`/usr/local/etc/ezjail/myjail_example_org`:

```
export jail_myjail_example_org_ip="192.168.3.6,127.0.0.1,::1"
```

**Comment by bdrewery** [comment]
Super old bug squashed!

c756e1822013a763c8a5e4ccee273794bd182e11 also helps.
