### ISSUE TITLE
"poudriere queue" is undocumented

### ISSUE THREAD

**Issue by ari** [freebsd/poudriere#333]
```sh
# /usr/local/bin/poudriere queue somequeue bulk -j 10 www/apache
{"type":"error","message":"No command specified"}

# /usr/local/bin/poudriere queue somequeue bulk
poudriere queue queuename poudriere_command

# /usr/local/bin/poudriere queue queuename bulk
poudriere queue queuename poudriere_command

# /usr/local/bin/poudriere queue somequeue "bulk -j 10 www/apache"
poudriere queue queuename poudriere_command

# echo "bulk -j 10 www/apache" | /usr/local/bin/poudriere queue somequeue
poudriere queue queuename poudriere_command

# /usr/local/bin/poudriere queue oncourse * bulk
====>> Error: distinfo command cannot be queued
```

OK, I give up. Please give us a hint...

**Comment by mat813** [comment]
There's a good reason it's not documented, it's because you should not use it.

**Comment by ari** [comment]
Then why is it in the man page? And in the in-app help? Why document it at all if it doesn't work and shouldn't be used? Why does it install a poudriered.conf sample file? And a rc.d script?

**Comment by bdrewery** [comment]
It's an "alpha" feature still in development. Needs documentation once it is decided how everything will interact with each other.

**Comment by ari** [comment]
Then for the sake of all the other people out there trying, getting frustrated by this, and wasting several hours, put something in the docs about not using this feature. Or just take the docs out entirely!

**Comment by koobs** [comment]
Agreed, remove it unless its ready for alpha testing, or mark it as [experimental] or [do not use]

**Comment by jeffsf** [comment]
I've got to agree that if it doesn't work, it shouldn't be on the man page. I've been trying unsuccessfully for  years to get it to work, especially so that I can get a slow machine to chug away on things without needing to stay connected to it.

There are a few hints that it has worked for some, such as http://savagedlight.me/2014/03/09/freebsd-package-builder-with-poudriere/ that make it seem as though it _should_ work, especially as the released man page indicates that it does.

**Comment by bdrewery** [comment]
I've marked it experimental with a hint on how to start it.

I don't want to remove it further from the manpage yet. We want it to be functional and the default way of building for 3.2.
