### ISSUE TITLE
Feature request: Web interface to include lists for "Queued" and "Remaining"

### ISSUE THREAD

**Issue by woodsb02** [freebsd/poudriere#386]
When viewing the poudriere web interface during a bulk build, it would be nice to be able to see a lists of all packages that were initially queued and all packages which are remaining.

As an optional extra, it would be nice if these 2 new lists included a "Reason" column (similar to that for skipped/ignored ports) which either stated the ports were explicitly requested to be built, or that they are being built because they are a dependency of port XXX.

**Comment by bdrewery** [comment]
The reason this hasn't been done yet is because it would really hurt the `bulk -a` builds of 24000 ports.

**Comment by bdrewery** [comment]
I'm not saying it won't happen though, just giving the reason for it missing so far.

**Comment by bdrewery** [comment]
I've added both of these. The remaining one requires setting `HTML_TRACK_REMAINING=1` in poudriere.conf due to performance reasons.

Both additions leave much to be desired but it's something at least.

I've also linked the dependency graph from the interface in f64c2d39f041cd36db53cbf6e61a6c7465e8995a

**Comment by woodsb02** [comment]
Thanks for this!

**Comment by bdrewery** [comment]
Yup, feel free to open another bug once you see it. It is seriously lacking due to the performance problems with it in the entire stack. From recording the data from bulk, to downloading a larger json file from the web interface, to the javascript having to redraw the entire remaining table (since it changes constantly). I was lazy with the redraw so it is very inefficient.  One of the big problems is the structure of the JSON file, it will be simpler to remedy with something like #440 rather than the awk scripts I use now.

**Comment by bdrewery** [comment]
And #415. In the stage of recording what was 'queued' I only have an ORIGIN, no PKGNAME yet.  That will conflict with FLAVORS.  For 'remaining' I only have a PKGNAME, no ORIGIN.  Both are hits due to performance.  What I need to do is export a pkgname: origin mapping in the JSON in 1 array as opposed to duplication that's in there now.

**Comment by bdrewery** [comment]
Hm, have a race from this...
```
/usr/bin/awk: can't open file exp-10amd64-commit-test/2017-06-06_04h00m53s/.poudriere.ports.remaining.tmp
 input record number 2, file exp-10amd64-commit-test/2017-06-06_04h00m53s/.poudriere.ports.remaining.tmp
 source line number 187
```
