### ISSUE TITLE
Under no circumstances destroy the whole zpool

### ISSUE THREAD

**Issue by mnd999** [freebsd/poudriere#471]
Managed to wipe an entire system doing something like:

`poudriere ports -c -M .`

It fails with a relative path error and then destroys the whole pool during cleanup.

**Comment by bdrewery** [comment]
Do you have a full log? The exact command ran and the error?

**Comment by mnd999** [comment]
Sadly not, the box was pretty hosed

**Comment by bdrewery** [comment]
Sorry. I'll update it to only destroy what it *successfully* creates.

**Comment by bdrewery** [comment]
```
~/git/poudriere # src/bin/poudriere -e /usr/local/etc api 'zfs_getfs .'
zroot/ROOT/head-r318116
```

**Comment by bdrewery** [comment]
This has actually been mitigated in `master` already.
In `release-3.1` we have this for `zfs_getfs`:
```
zfs_getfs() {
        [ $# -ne 1 ] && eargs zfs_getfs mnt
        local mnt="${1}"
        local mntres

        mntres=$(realpath "${mnt}" 2>/dev/null || echo "${mnt}")
        mount -t zfs | awk -v n="${mntres}" ' $3 == n { print $1 }'
}
```

So it will find the actual ZFS mountpoint for whatever path is passed in. In the example above `zfs_getfs .` returned the root pool.

In `master` though the situation is better since it is limited to poudriere's own `ZPOOL`:
```
_zfs_getfs() {
        [ $# -ne 1 ] && eargs _zfs_getfs mnt
        local mnt="${1}"

        mntres=$(realpath "${mnt}" 2>/dev/null || echo "${mnt}")
        zfs list -rt filesystem -H -o name,mountpoint ${ZPOOL}${ZROOTFS} | \
            awk -vmnt="${mntres}" '$2 == mnt {print $1}'
}
```

This was done in 7d6511d423e85c9b36bc4bc2bc1a1398565e1757 to actually fix a case where the pool *wasn't* deleted since it was never mounted.  So it would have prevented wiping the zroot in this case.
However the situation is not fully right yet as with that fix `destroyfs` falls back to wiping the path passed in if ZFS didn't know about it:
```
[ "${fs}" != "none" ] && fs=$(zfs_getfs ${mnt})
if [ -n "${fs}" -a "${fs}" != "none" ]; then
        zfs destroy -rf ${fs}
        rmdir ${mnt} || :
        # Must invalidate the zfs_getfs cache.
        cache_invalidate _zfs_getfs "${mnt}"
else
        [ -d ${mnt} ] || return 0
        rm -rfx ${mnt} 2>/dev/null || :
        if [ -d "${mnt}" ]; then
                chflags -R 0 ${mnt}
                rm -rfx ${mnt}
        fi
fi
```

So it would have done `rm -rf .`

**Comment by bdrewery** [comment]
With new fix:

```
~/git/poudriere # src/bin/poudriere -e /usr/local/etc ports -c -p hm -M .
[00:00:00] ====>> Error: Directory . already exists
```
