### ISSUE TITLE
PREPARE_PARALLEL_JOBS should limit parallelism until actual build

### ISSUE THREAD

**Issue by reezer** [freebsd/poudriere#475]
When setting PREPARE_PARALLEL_JOBS to 1 I see poudriere still running multiple build-depends, runtime-depends and extract jobs.

Since PREPARE_PARALLEL_JOBS is meant to reduce the outstanding i/o I think it should limit everything but the actual build/compile stage.

**Comment by bdrewery** [comment]
Those depends calls are in the actual "port build" phase. The PREPARE_PARALLEL_JOBS is purely for the startup of computing dependencies - long before the "port build" phase. 

It's not possible to do as you ask.

The structure of Poudriere is:
1. compute dependencies.
 - This iterates all ports in the queue and asks them what their BUILD_DEPENDS LIB_DEPENDS PKGNAME, etc, are.
  - It parallelizes this by PREPARE_PARALLEL_JOBS since it is just simple `make -V` calls and not compliations.
2. It then loads up PARALLEL_JOBS "builders" or jails.
3. It then passes jobs from the queue to idle builders.
4. Idle builders do the "port build" phase, where they do everything from installing dependencies in the jail (which is what build-depends, lib-depends, etc are).  Then they do the actual compilation and packaging.

It's not possible to limit the depends installation part of the port build phases because the job has already been doled out to one of the idle builders which was determined by PARALLEL_JOBS.

It's quite similar to the problem discussed in #387 that we can't really change MAKE_JOBS/cpus dynamically. Once a job is dispatched it will use whatever MAKE_JOBS or cpus we gave it at the start.


Anyway, with 3.2 (poudriere-devel) the PREPARE_PARALLEL_JOBS phases of computing dependencies are much faster and parallelize better.

Are you building over NFS or some other slow IO?
