### ISSUE TITLE
Ports tree "default" is currently mounted and being used.

### ISSUE THREAD

**Issue by nbari** [freebsd/poudriere#579]
I often see this error, when for unknown reasons the jails just don't terminate and get stuck.

    Ports tree "default" is currently mounted and being used.
   
Is there a way to removing all the jails created by poudriere (avoiding a reboot)

**Comment by grahamperrin** [comment]
Is this still an issue? 

Maybe of interest, FreeBSD bugs: 

* [253553 – sysutils/lsof: no zfs support on 13](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253553)
* [254024 – devel/gvfs: gvfsd-trash latches to zfs volumes](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254024), although I have never seen this process interfere with a poudriere-related mount.

**Comment by nbari** [comment]
Hi @grahamperrin thanks for the links, I will close the issue for now since I haven't seen this issue recently.

**Comment by infostud** [comment]
poudriere version
poudriere-git-3.4.99.20250209
freebsd-version 
14.3-RELEASE

I use Buildbot to manage remote poudriere builds.
Python version: 3.11.10
Buildbot version: 3.11.9
Twisted version: 24.7.0

sudo poudriere ports -u -p default -v
Error: /usr/local/share/poudriere/ports.sh:359:Ports tree "default" is currently mounted and being used.
program finished with exit code 1

Previous build stops because of some port issue like
Error: MOVED: devel/py-pytest-runner EXPIRED 2025-06-23 Has expired: pytest-runner depends on deprecated features of setuptools

I'm running in jails so it is easy to restart them but shouldn't be necessary:
[00:00:09] Cleaning up
[00:00:09] Unmounting file systems
program finished with exit code 1
elapsedTime=9.710340
