### ISSUE TITLE
Different flavors should not cause "incorrectly  depends on itself"-error

### ISSUE THREAD

**Issue by uzsolt** [freebsd/poudriere#582]
I'm trying the flavors and if a port depends itself with different flavor (for example foo@gui depends on foo@lib) poudriere displays _"incorrectly  depends on itself"_ message. I think it should be allowed.
https://github.com/freebsd/poudriere/blob/master/src/share/poudriere/common.sh#L5668

**Comment by bdrewery** [comment]
This is strongly intended and even fixed further in 3.2.4 for testport.
FLAVORS are intended to provide OPTION/default version differences, not become some sub-package meta package thing where a port makes a FLAVOR for each individual file and then depends on itself as a master meta package that has no files otherwise.

_gui_ and _lib_ are different packages, or sub-packages, not different FLAVORS.
Ports does not have sub-package support yet.
