### ISSUE TITLE
testport subcommand does not work in locked down environment

### ISSUE THREAD

**Issue by michael-o** [freebsd/poudriere#670]
When testing a port in a locked down environment `fetch(1)` cannot download any port sources. This can easibly fixed in `/usr/local/bin/poudriere` by saying:

    case "${CMD}" in
      ports|jail|testport)

This passed  proxy information down to the jail.

Willing to provide a PR for that.

**Comment by bdrewery** [comment]
This one is weird and annoying but intended.
```
src/etc/poudriere.conf.sample:# export HTTP_PROXY=bla
src/etc/poudriere.conf.sample:# export FTP_PROXY=bla
```
Because the ports build down in a jail for `bulk` and `testport` we want its environment to be clearly stated in the config for package build consistency.

I don't necessarily even buy my own argument. I'm not sure why I added the passthroughs for `jail` and `ports` when `export` was the documented way. I'd like to see more discussion about changing this to extend to `bulk` and `testport`.

Thinking about future plans for distributed though these variables really should be in the config since the environment `poudriere` is ran in won't be exported down to the slaves.

**Comment by michael-o** [comment]
From a users perspective, this is highly inconsistent. I don't see apparently a difference between those commands. Moreover, I'd expect `poudriere.conf` to mention that these vars are only for subcommand `X`. Please also add `NO_PROXY` to `poudriere.conf`.

BTW, if you run `poudirere port` with Subversion it won't work anyway because libserf does not read these variables. You must configure the proxy with Subversion anyway.

**Comment by bdrewery** [comment]
> From a users perspective, this is highly inconsistent. I don't see apparently a difference between those commands. Moreover, I'd expect `poudriere.conf` to mention that these vars are only for subcommand `X`. Please also add `NO_PROXY` to `poudriere.conf`.
> 

You can put whatever you into poudriere.conf as `export` and it applies to all commands.
For that reason is why I wonder why I added any passthrough for these for `ports` and `jail`.

> BTW, if you run `poudirere port` with Subversion it won't work anyway because libserf does not read these variables. You must configure the proxy with Subversion anyway.

As documented the flags are only intended for `fetch`.

**Comment by michael-o** [comment]
OK, I see, I rather go for explicity and drop the passthrough. poudriere.conf worked for me today.

**Comment by michael-o** [comment]
Closing as resolved.
