### ISSUE TITLE
Problem compiling kde5 libieee issue on amd64

### ISSUE THREAD

**Issue by justfly1111** [freebsd/poudriere#808]
## Prerequisites
- [ yes] Have you checked for an existing issue describing the issue?

So I’m trying to compile kde5 which ends up getting skipped because poudriere refuses to compile libieee saying it’s only for i386 there was no issues on my old Xeon box but since switching over to my and thread ripper it won’t compile i386 library that kde needs any fixes so I’m able to compile this with kde???

**Comment by bdrewery** [comment]
Sorry there's not enough information here to help and this is very unlikely a Poudriere issue. We would need to know what your jail version is, what arch, what version and arch your host is, which ports tree, and some build logs because I don't know where libieee is located.

I suggest freebsd-ports@FreeBSD.org or #bsdports on IRC EFNet.
