### ISSUE TITLE
Interrupting a testport at early stage leads to killing host daemons

### ISSUE THREAD

**Issue by AMDmi3** [freebsd/poudriere#977]
FreeBSD 13.0, poudriere-devel-3.3.99.20211130

When `poudriere testport` is interrupted (^C) right after `Creating the reference jail...` message, it kills host processes via pidfiles in (host) `/var/run`. I've traced it up to `jail_cleanup` which is called from `exit_handler`, and it looks like `MASTER_DATADIR` is empty in this case.

https://github.com/freebsd/poudriere/blob/42d74766e179794caf9f4d9ccf39de98348c5bca/src/share/poudriere/common.sh#L3470-L3478

It may need a condition similar to https://github.com/freebsd/poudriere/commit/04719b571fe147bf1a4b26faa27a89bf549e2fa0, or `MASTER_DATADIR` may need to be set earlier.

**Comment by bdrewery** [comment]
Thank you. I've fixed it locally and will push it out when I get a chance.
I plan to make Poudriere work with `set -u` after this. `kill_job` was also getting an exit status of `127` for each process it killed which shouldn't happen so I'll add assert that it does not happen again.

**Comment by jdwx** [comment]
FWIW, I have also observed this behavior (poudriere killing processes with pidfiles in /var/run) from `poudriere bulk`.

In our case, it was caused by accidentally removing the @clean snapshot from a build environment.  That does make reproducing the problem consistent and non-interactive, which might help develop a test case if needed.

(This was on poudriere-devel-3.3.99.20220831 from ports.)
